# Site
repository: coolhva/coolhva.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Henk van Achterberg
title: Technical Architect for Zero Trust
email: henk@vanachterberg.org
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://www.vanachterberg.org
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: coolhva
github_username:  coolhva
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
facebook_username: coolhva
flickr_username: coolhva
instagram_username: coolhva
linkedin_username: henkva
#xing_username: jekyll
#pinterest_username: jekyll
youtube_username: coolhva@gmail.com
#googleplus_username: +coolhva
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-4456753-1"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | 
  Technology is my passion and after working in IT for a long time I now focus on Cyber Security, please check out my LinkedIn for my corporate profile.

  This page is mainly about my personal interests and hobby projects.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: USG with KPN FTTH
        link: https://coolhva.github.io/usg-kpn-ftth/posts/unifi-security-gateway-kpn-ftth-iptv-ipv6/
        link_text: Dutch manual
        quote: >
          Be in control with your own hardware on your internet connection
        description: | # this will include new lines to allow paragraphs
          With KPN, a dutch internet provider, you can use your own hardware but that was not easy as there are a lot of moving parts.
          For my own network at home I managed to get it working with the Unifi Security Gateway and I shared my configuration with others.
          Still a lot of questions came from people that were having challenges and for them I wrote a (Dutch) manual.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
